login/urls.py
from django.urls import path,include
from . import views

app_name = 'login'

urlpatterns = [
    path('',views.index, name="index"),
    path('registration/',views.registration, name="registration"),
    path('login/',views.user_login, name="user_login"),
    path('logout/',views.user_logout, name="user_logout"),

    path('activation_account/<uidb64>/<token>/', views.activate_account, name='activate_account'),
]

quiz_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('test/', include('quizes.urls')),
    path('', include('login.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

login/models.py
from django.db import models

# Create your models here.

login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User, UserManager
import datetime

class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields=(
            'username',
            'email',
            'first_name', 
            'last_name', 
            'password1', 
            'password2'
            )

"""
Email = forms.EmailField()
First_Name = forms.CharField()
Last_Name = forms.CharField()
Birthday = forms.forms.DateField(initial=datetime.date.today)
"""

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

login/views.py
from django.http.request import HttpRequest
from django.http.response import HttpResponse

from django.shortcuts import redirect, render

from django.db import IntegrityError
from django.core.exceptions import ValidationError

from django.contrib import auth, messages
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site

from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_text, force_bytes
from django.template.loader import render_to_string


from .tokens import account_activation_token
from .forms import RegistrationForm, LoginForm
# Create your views here.
@login_required
def index(request):
    return render(request,"index.html")

###LOGIN###
def user_login(request):
    data = {}
    template_name = 'login.html'
    if request.user.is_authenticated:
        return redirect('login:index')
    else:
        if request.POST:
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(
                username=username,
                password=password
            )
            if user is not None:
                if user.is_active:
                    auth.login(request, user)
                    messages.add_message(
                        request,
                        messages.SUCCESS,
                        'Inicio de Sesión Correcto.'
                    )
                    return redirect('login:index')
                else:
                    messages.add_message(
                        request,
                        messages.ERROR,
                        'Cuenta No Activada. Por favor, comprueba la bandeja de entrada de tu correo electrónico.'
                    )
            else:
                messages.add_message(
                    request,
                    messages.SUCCESS,
                    'Datos Incorrectos.'
                )

    return render(request, template_name, data)

@login_required
def user_logout(request):
    logout(request)
    return redirect('login:index')

def activate_account(request, uidb64, token):
    data = {}
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        messages.add_message(
            request,
            messages.SUCCESS,
            'Cuenta Activada!.'
        )
        return redirect('login:index')
    else:
        messages.add_message(
            request,
            messages.ERROR,
            'Su cuenta no pudo ser activada!.'
        )
        return redirect('login:index')

def registration(request):
    data = {}
    template_name = 'registration.html'
    if request.method == "POST":
        data['form'] = RegistrationForm(request.POST)
        if data['form'].is_valid():
            data['form'].save()
            try:
                user = data['form'].save()
                user.refresh_from_db()
                user.is_active = False
                user.save()
                current_site = get_current_site(request)
                subject = 'StartMATH - Activa tu cuenta.'
                message = render_to_string('activation.html', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': account_activation_token.make_token(user),
                })
                user.email_user(subject, message)
                messages.add_message(
                    request,
                    messages.SUCCESS,
                    'Activa tu Cuenta.'
                )
                return redirect('login:index')

            except IntegrityError as ie:
                messages.add_message(
                    request,
                    messages.ERROR,
                    'Error mientras se registra usuario: {error}.'.format(error=str(ie))
                )

            except ValidationError as ve:
                messages.add_message(
                    request,
                    messages.ERROR,
                    'Problemas con la validación del formulario: {error}.'.format(error=str(ve))
                )
        else:
            messages.add_message(
                request,
                messages.ERROR,
                'Error mientras se registra usuario.'
            )

    else:
        data['form'] = RegistrationForm()

    return render(request, template_name, data)

login/templates/activation.html
{% autoescape off %}
Hi {{ user.username }},

Please click the following link to confirm your registration:

http://{{ domain }}{% url 'login:activate_account' uidb64=uid token=token %}
{% endautoescape %}	

login/templates/base_login.html
{% load static %}
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="utf-8" />
	<title>Color Admin | Login Page</title>
	<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
	<meta content="" name="description" />
	<meta content="" name="author" />
	
	<!-- ================== BEGIN BASE CSS STYLE ================== -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />

	<link href='{% static "assets/plugins/bootstrap/css/bootstrap.min.css" %}' rel="stylesheet" />
	<link href='{% static "/assets/plugins/font-awesome/css/all.min.css" %}' rel="stylesheet" />
	<link href='{% static "/assets/plugins/animate/animate.min.css" %}' rel="stylesheet" />
	<link href='{% static "/assets/css/default/style.min.css" %}' rel="stylesheet" />
	<link href='{% static "/assets/css/default/style-responsive.min.css" %}' rel="stylesheet" />
	<link href='{% static "/assets/css/default/theme/default.css" %}' rel="stylesheet" id="theme" />
	<!-- ================== END BASE CSS STYLE ================== -->
	
	<!-- ================== BEGIN BASE JS ================== -->
	<script src='{% static "/assets/plugins/pace/pace.min.js" %}'></script>
	<!-- ================== END BASE JS ================== -->
</head>
<body class="pace-top bg-white">
	<!-- begin #page-loader -->
	<div id="page-loader" class="fade show"><span class="spinner"></span></div>
	<!-- end #page-loader -->
	
	<!-- begin #page-container -->
	{% block content %}
	{% endblock content %}
	<!-- end page container -->
	
	<!-- ================== BEGIN BASE JS ================== -->
	<script src='{% static "/assets/plugins/jquery/jquery-3.3.1.min.js" %}'></script>
	<script src='{% static "/assets/plugins/jquery-ui/jquery-ui.min.js" %}'></script>
	<script src='{% static "/assets/plugins/bootstrap/js/bootstrap.bundle.min.js" %}'></script>
	<script src='{% static "/assets/plugins/slimscroll/jquery.slimscroll.min.js" %}'></script>
	<script src='{% static "/assets/plugins/js-cookie/js.cookie.js" %}'></script>
	<script src='{% static "/assets/js/theme/default.min.js" %}'></script>
	<script src='{% static "/assets/js/apps.min.js" %}'></script>
	<!-- ================== END BASE JS ================== -->

	<script>
		$(document).ready(function() {
			App.init();
		});
	</script>
</body>
</html>

login/templates/index.html
{% extends "base_login.html" %}
{% load bootstrap4 %}
{% load static %}

{% block title %}

{% endblock title %}

{% block content %}
    <div id="page-container" class="fade">
        {% if request.user.is_authenticated %}
        <nav class="navbar navbar-dark bg-dark">
            <span class="navbar-brand mb-0 h1">BLC</span>
        </nav> 
        <h1> Welcome to STARTMATH </h1>


        <h1> Welcome {{request.user.username}}</h1>
        <span>{% bootstrap_messages %}</span>
        
        <a href="{% url 'login:user_logout' %}"class= "btn btn-lg btn-success ml-5">logout</a>
        {% endif %}
    </div>
{% endblock content %}

login/templates/login.html
{% extends "base_login.html" %}
{% load bootstrap4 %}
{% load static %}

{% block title %}

{% endblock title %}

{% block content %}
    <div id="page-container" class="fade">
        <!-- begin login -->
        <div class="login login-with-news-feed">
            <!-- begin news-feed -->
            <div class="news-feed">
                <div class="news-image" style="background-image: url({% static '/assets/img/login-bg/login-bg-11.jpg' %})"></div>
                <div class="news-caption">
                    <h4 class="caption-title"><b>Color</b> Admin App</h4>
                    <p>
                        Download the Color Admin app for iPhone®, iPad®, and Android™. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    </p>
                </div>
            </div>
            <!-- end news-feed -->
            <!-- begin right-content -->
            <div class="right-content">
                <!-- begin login-header -->
                <div class="login-header">
                    <div class="brand">
                        <span class="logo"></span> <b>Color</b> Admin
                        <small>responsive bootstrap 4 admin template</small>
                    </div>
                    <div class="icon">
                        <i class="fa fa-sign-in"></i>
                    </div>
                </div>
                <!-- end login-header -->
                <!-- begin login-content -->
                <div class="login-content">
                    <form action="." method="POST" class="margin-bottom-0">
                        {% csrf_token %}
                        <div class="form-group m-b-20">
                            <input type="text" class="form-control form-control-lg" id="username" name="username" placeholder="Usuario" required />
                        </div>
                        <div class="form-group m-b-20">
                            <input type="password" class="form-control form-control-lg" id="inputPassword" name="password" placeholder="Contraseña" required />
                        </div>
                        <div class="checkbox checkbox-css m-b-30">
                            <input type="checkbox" id="remember_me_checkbox" value="" />
                            <label for="remember_me_checkbox">
                            Remember Me
                            </label>
                        </div>
                        <div class="login-buttons">
                            <button type="submit" class="btn btn-success btn-block btn-lg">Sign me in</button>
                        </div>
                        <div class="m-t-20 m-b-40 p-b-40 text-inverse">
                            Not a member yet? Click <a href="{% url 'login:registration' %}" class="text-success">here</a> to register.
                        </div>
                        <hr />
                        <p class="text-center text-grey-darker">
                            &copy; Color Admin All Right Reserved 2019
                        </p>
                    </form>
                </div>
                <!-- end login-content -->
            </div>
            <!-- end right-container -->
        </div>
        <!-- end login -->
    </div>
{% endblock content %}

login/templates/registration.html
{% extends "base_login.html" %}
{% load bootstrap4 %}
{% load static %}

{% block title %}

{% endblock title %}

{% block content %}
	<!-- begin #page-container -->
	<div id="page-container" class="fade">
		<!-- begin register -->
		<div class="register register-with-news-feed">
			<!-- begin news-feed -->
			<div class="news-feed">
				<div class="news-image" style="background-image: url({% static '/assets/img/login-bg/login-bg-9.jpg' %})"></div>
				<div class="news-caption">
					<h4 class="caption-title"><b>Color</b> Admin App</h4>
					<p>
						As a Color Admin app administrator, you use the Color Admin console to manage your organization’s account, such as add new users, manage security settings, and turn on the services you want your team to access.
					</p>
				</div>
			</div>
			<!-- end news-feed -->
			<!-- begin right-content -->
			<div class="right-content">
				<!-- begin register-header -->
				<h1 class="register-header">
					Sign Up
					<small>Create your Color Admin Account. It’s free and always will be.</small>
				</h1>
				<!-- end register-header -->
				<!-- begin register-content -->
				<div class="register-content">
					<form action= "." method="POST" class="margin-bottom-0">
                        {% bootstrap_messages %}
                        {% csrf_token %}
                        {% bootstrap_form form %}
						<div class="register-buttons">
							<button type="submit" class="btn btn-primary btn-block btn-lg">Sign Up</button>
						</div>
						<div class="m-t-20 m-b-40 p-b-40 text-inverse">
							Already a member? Click <a href="{% url 'login:user_logout' %}">here</a> to login.
						</div>
						<hr />
						<p class="text-center">
							&copy; Color Admin All Right Reserved 2019
						</p>
					</form>
				</div>
				<!-- end register-content -->
			</div>
			<!-- end right-content -->
		</div>
		<!-- end register -->
{% endblock content %}