login/urls.py
from django.urls import path,include
from . import views

app_name = 'login'

urlpatterns = [
    path('',views.index, name="index"),
    path('registration/',views.registration, name="registration"),
    path('login/',views.user_login, name="user_login"),
    path('logout/',views.user_logout, name="user_logout"),

    path('activation_account/<uidb64>/<token>/', views.activate_account, name='activate_account'),
]

quiz_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('test/', include('quizes.urls')),
    path('', include('login.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quizes/urls.py
from django.urls import path
from .views import (
    QuizListView,
    quiz_view,
    quiz_data_view,
    save_quiz_view
)

app_name = 'quizes'

urlpatterns = [
    path('', QuizListView.as_view(), name='main-view'),
    path('<pk>/', quiz_view, name='quiz-view'),
    path('<pk>/save/', save_quiz_view, name='save-view'),
    path('<pk>/data/', quiz_data_view, name='quiz-data-view'),
]

quizes/models.py
from django.db import models
import random

DIFF_CHOICES = (
    ('easy', 'easy'),
    ('medium', 'medium'),
    ('hard', 'hard'),
)

class Quiz(models.Model):
    name = models.CharField(max_length=120)
    topic = models.CharField(max_length=120)
    number_of_questions = models.IntegerField()
    time = models.IntegerField(help_text="duration of the quiz in minutes")
    required_score_to_pass = models.IntegerField(help_text="required score in %")
    difficulty = models.CharField(max_length=6, choices=DIFF_CHOICES)

    def __str__(self):
        return f"{self.name}-{self.topic}"

    def get_questions(self):
        questions = list(self.question_set.all())
        random.shuffle(questions)
        return questions[:self.number_of_questions]

    class Meta:
        verbose_name_plural = 'Quizes'

quizes/views.py
from django.shortcuts import render
from .models import Quiz
from django.views.generic import ListView
from django.http import JsonResponse
from questions.models import Question, Answer
from results.models import Result

class QuizListView(ListView):
    model = Quiz 
    template_name = 'quizes/main.html'

def quiz_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    return render(request, 'quizes/quiz.html', {'obj': quiz})

def quiz_data_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    questions = []
    for q in quiz.get_questions():
        answers = []
        for a in q.get_answers():
            answers.append(a.text)
        questions.append({str(q): answers})
    return JsonResponse({
        'data': questions,
        'time': quiz.time,
    })

def save_quiz_view(request, pk):
    if request.is_ajax():
        questions = []
        data = request.POST
        data_ = dict(data.lists())

        data_.pop('csrfmiddlewaretoken')

        for k in data_.keys():
            print('key: ', k)
            question = Question.objects.get(text=k)
            questions.append(question)
        print(questions)

        user = request.user
        quiz = Quiz.objects.get(pk=pk)

        score = 0
        multiplier = 100 / quiz.number_of_questions
        results = []
        correct_answer = None

        for q in questions:
            a_selected = request.POST.get(q.text)

            if a_selected != "":
                question_answers = Answer.objects.filter(question=q)
                for a in question_answers:
                    if a_selected == a.text:
                        if a.correct:
                            score += 1
                            correct_answer = a.text
                    else:
                        if a.correct:
                            correct_answer = a.text

                results.append({str(q): {'correct_answer': correct_answer, 'answered': a_selected}})
            else:
                results.append({str(q): 'not answered'})
            
        score_ = score * multiplier
        Result.objects.create(quiz=quiz, user=user, score=score_)

        if score_ >= quiz.required_score_to_pass:
            return JsonResponse({'passed': True, 'score': score_, 'results': results})
        else:
            return JsonResponse({'passed': False, 'score': score_, 'results': results})

quizes/templates/quizes/main.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
    <script src="{% static 'quizes/main.js' %}" defer></script> 
{% endblock scripts %}

{% block title %}
home
{% endblock title %}

{% block content %}

<!-- Modal -->
<div class="modal fade" id="quizStartModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Start?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="modal-body-confirm"></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">no</button>
        <button type="button" id="start-button" class="btn btn-success">yes</button>
      </div>
    </div>
  </div>
</div>

<div class="h1">Quiz List</div>
<hr>
{% for obj in object_list %}
    <button
        class="btn btn-link modal-button"
        data-pk="{{obj.pk}}"
        data-quiz="{{obj.name}}"
        data-questions="{{obj.number_of_questions}}"
        data-difficulty="{{obj.difficulty}}"
        data-time="{{obj.time}}"
        data-pass = "{{obj.required_score_to_pass}}"
        data-toggle="modal"
        data-target="#quizStartModal">
        {{obj.name}}
    </button><br>

{% endfor %}
{% endblock content %}

quizes/templates/quizes/quiz.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
    <script src="{% static 'quizes/quiz.js' %}" defer></script> 
{% endblock scripts %}

{% block title %}
{{obj.name}}
{% endblock title %}

{% block content %}

<div class="row">
    <div class="col">
        <b>{{obj.name}}</b>
        <p>score to pass: {{obj.required_score_to_pass}}%</p>
    </div>
    <div class="col text-right" id="timer-box"></div>
</div>

<a href="{% url 'quizes:main-view' %}" class="btn btn-danger">go back</a>

<form id="quiz-form" class="mt-3 mb-3">
    {% csrf_token %}
    <div id="quiz-box"></div>
    <button type="submit" class="btn btn-primary mt-3">save</button>
</form>
<div id="score-box"></div>
<div id="result-box"></div>
{% endblock content %}